apiVersion: v1
kind: Namespace
metadata:
  name: llmsafespace-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller
  namespace: llmsafespace-system
  labels:
    app: controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: controller
  template:
    metadata:
      labels:
        app: controller
    spec:
      serviceAccountName: controller
      containers:
      - name: manager
        image: llmsafespace/controller:latest
        args:
        - --metrics-addr=:8080
        - --health-probe-bind-address=:8081
        - --enable-leader-election
        ports:
        - containerPort: 8080
          name: metrics
        - containerPort: 8081
          name: health
        - containerPort: 9443
          name: webhook
        livenessProbe:
          httpGet:
            path: /healthz
            port: health
        readinessProbe:
          httpGet:
            path: /readyz
            port: health
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: controller
  namespace: llmsafespace-system
spec:
  selector:
    app: controller
  ports:
  - port: 443
    targetPort: 9443
    name: webhook
  - port: 8080
    targetPort: 8080
    name: metrics
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: controller
  namespace: llmsafespace-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: controller
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["llmsafespace.dev"]
  resources: ["sandboxes", "sandboxprofiles", "warmpools", "warmpods", "runtimeenvironments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["llmsafespace.dev"]
  resources: ["sandboxes/status", "warmpools/status", "warmpods/status", "runtimeenvironments/status"]
  verbs: ["get", "update", "patch"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: controller
subjects:
- kind: ServiceAccount
  name: controller
  namespace: llmsafespace-system
