import { useState, useEffect } from "react";
import { messagesApi } from "../api/messages";
import { ApiClientError } from "../api/client";
import type { Message } from "../api/types";

export type QueuedMessage = {
  id: string;
  text: string;
  sentAt: number;
  status: "pending" | "error";
  error?: string;
};

// Generate a message ID that matches opencode's ascending ULID-style scheme:
//   msg_ + 12 hex chars (timestamp * 0x1000 + counter) + 14 base62 chars
// opencode's latest() resolves the active user message by lexicographic max ID,
// so IDs generated here must sort consistently with IDs generated by opencode
// internally. UUID-based IDs (e.g. "msg_feeb1f32-...") can permanently
// outrank ULID-style IDs ("msg_eb..."), breaking model-switch and loop recovery.
let _lastTs = 0;
let _counter = 0;
const BASE62 = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz";

function uid(): string {
  const now = Date.now();
  if (now !== _lastTs) { _lastTs = now; _counter = 0; }
  _counter++;

  // Encode timestamp * 0x1000 + counter into 6 bytes, big-endian hex (12 chars)
  let ts = BigInt(now) * BigInt(0x1000) + BigInt(_counter);
  const timeBytes: number[] = [];
  for (let i = 0; i < 6; i++) {
    timeBytes.unshift(Number(ts & BigInt(0xff)));
    ts >>= BigInt(8);
  }
  const timeHex = timeBytes.map((b) => b.toString(16).padStart(2, "0")).join("");

  // 14 random base62 chars
  const randBytes =
    typeof crypto !== "undefined" && crypto.getRandomValues
      ? crypto.getRandomValues(new Uint8Array(14))
      : new Uint8Array(14).map(() => Math.floor(Math.random() * 256));
  let rand = "";
  for (let i = 0; i < 14; i++) rand += BASE62[randBytes[i]! % 62];

  return timeHex + rand;
}

export function useMessageQueue(
  workspaceId: string | undefined,
  sessionId: string | undefined,
) {
  const [queuedMessages, setQueuedMessages] = useState<QueuedMessage[]>([]);

  const enqueue = (text: string) => {
    if (!workspaceId || !sessionId) return;
    const id = "msg_" + uid();
    const msg: QueuedMessage = { id, text, sentAt: Date.now(), status: "pending" };
    setQueuedMessages((prev) => [...prev, msg]);

    messagesApi
      .sendAsync(workspaceId, sessionId, {
        parts: [{ type: "text", text }],
        messageID: id,
      })
      .catch((err: unknown) => {
        let error = err instanceof Error ? err.message : "Failed to send";
        if (err instanceof ApiClientError && err.status === 429) {
          const retryAfter = ((err.body as unknown) as Record<string, unknown>).retryAfter ?? 60;
          error = `Rate limited. Retry after ${retryAfter}s`;
        }
        setQueuedMessages((prev) =>
          prev.map((m) => (m.id === id ? { ...m, status: "error", error } : m)),
        );
      });
  };

  const remove = (id: string) => {
    setQueuedMessages((prev) => prev.filter((m) => m.id !== id));
  };

  const clear = () => setQueuedMessages([]);

  const reconcile = (history: Message[]) => {
    const historyIds = new Set(history.filter((m) => m.role === "user").map((m) => m.id));
    setQueuedMessages((prev) => prev.filter((m) => !historyIds.has(m.id)));
  };

  const retry = async (id: string) => {
    if (!workspaceId || !sessionId) return;
    const msg = queuedMessages.find((m) => m.id === id);
    if (!msg || msg.status !== "error") return;

    try {
      const history = await messagesApi.getHistory(workspaceId, sessionId);
      if (history.some((m) => m.id === id)) {
        remove(id);
        return;
      }
    } catch { /* history fetch failed — fall through to retry send */ }

    setQueuedMessages((prev) =>
      prev.map((m) =>
        m.id === id ? { ...m, status: "pending", error: undefined, sentAt: Date.now() } : m,
      ),
    );

    messagesApi
      .sendAsync(workspaceId, sessionId, {
        parts: [{ type: "text", text: msg.text }],
        messageID: id,
      })
      .catch((err: unknown) => {
        let error = err instanceof Error ? err.message : "Failed to send";
        if (err instanceof ApiClientError && err.status === 429) {
          const retryAfter = ((err.body as unknown) as Record<string, unknown>).retryAfter ?? 60;
          error = `Rate limited. Retry after ${retryAfter}s`;
        }
        setQueuedMessages((prev) =>
          prev.map((m) => (m.id === id ? { ...m, status: "error", error } : m)),
        );
      });
  };

  const dismiss = (id: string) => remove(id);

  const onPhaseChange = (phase: string) => {
    if (phase === "Creating" || phase === "Pending" || phase === "Suspending") {
      setQueuedMessages((prev) =>
        prev.map((m) =>
          m.status === "pending" ? { ...m, status: "error", error: "Workspace restarted" } : m,
        ),
      );
    }
  };

  useEffect(() => {
    const interval = setInterval(() => {
      const now = Date.now();
      setQueuedMessages((prev) =>
        prev.map((m) =>
          m.status === "pending" && now - m.sentAt > 90_000
            ? { ...m, status: "error", error: "Timed out" }
            : m,
        ),
      );
    }, 15_000);
    return () => clearInterval(interval);
  }, []);

  return { queuedMessages, enqueue, remove, retry, dismiss, clear, reconcile, onPhaseChange };
}
