import { useState, useCallback } from "react";
import { messagesApi } from "../api/messages";
import { ApiClientError } from "../api/client";
import type { Message } from "../api/types";

export type QueuedMessage = {
  id: string;
  text: string;
  status: "pending" | "sending" | "error";
  error?: string;
};

// Generate a message ID that matches opencode's ascending ULID-style scheme:
//   msg_ + 12 hex chars (timestamp * 0x1000 + counter) + 14 base62 chars
// opencode's latest() resolves the active user message by lexicographic max ID,
// so IDs generated here must sort consistently with IDs generated by opencode
// internally. UUID-based IDs (e.g. "msg_feeb1f32-...") can permanently
// outrank ULID-style IDs ("msg_eb..."), breaking model-switch and loop recovery.
let _lastTs = 0;
let _counter = 0;
const BASE62 = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz";

function uid(): string {
  const now = Date.now();
  if (now !== _lastTs) { _lastTs = now; _counter = 0; }
  _counter++;

  // Encode timestamp * 0x1000 + counter into 6 bytes, big-endian hex (12 chars)
  let ts = BigInt(now) * BigInt(0x1000) + BigInt(_counter);
  const timeBytes: number[] = [];
  for (let i = 0; i < 6; i++) {
    timeBytes.unshift(Number(ts & BigInt(0xff)));
    ts >>= BigInt(8);
  }
  const timeHex = timeBytes.map((b) => b.toString(16).padStart(2, "0")).join("");

  // 14 random base62 chars
  const randBytes =
    typeof crypto !== "undefined" && crypto.getRandomValues
      ? crypto.getRandomValues(new Uint8Array(14))
      : new Uint8Array(14).map(() => Math.floor(Math.random() * 256));
  let rand = "";
  for (let i = 0; i < 14; i++) rand += BASE62[randBytes[i]! % 62];

  return timeHex + rand;
}

export function useMessageQueue(
  workspaceId: string | undefined,
  sessionId: string | undefined,
) {
  const [queuedMessages, setQueuedMessages] = useState<QueuedMessage[]>([]);

  // Send the first pending item in the queue. Called when the session goes idle.
  // Matches TUI behavior: remove the item from the queue as soon as promptAsync
  // returns 204, then the next notifyIdle (from the server's session.status=idle
  // after processing) will drain the next item.
  const drainOne = useCallback((msgs: QueuedMessage[]) => {
    if (!workspaceId || !sessionId) return;
    const head = msgs.find((m) => m.status === "pending");
    if (!head) return;

    // Mark as sending
    setQueuedMessages((prev) =>
      prev.map((m) => m.id === head.id ? { ...m, status: "sending" } : m),
    );

    messagesApi
      .sendAsync(workspaceId, sessionId, {
        parts: [{ type: "text", text: head.text }],
        messageID: head.id,
      })
      .then(() => {
        // 204 received — remove from queue immediately (TUI behavior).
        // The next session.status=idle event will drain the next item.
        setQueuedMessages((prev) => prev.filter((m) => m.id !== head.id));
      })
      .catch((err: unknown) => {
        let error = err instanceof Error ? err.message : "Failed to send";
        if (err instanceof ApiClientError && err.status === 429) {
          const retryAfter = ((err.body as unknown) as Record<string, unknown>).retryAfter ?? 60;
          error = `Rate limited. Retry after ${retryAfter}s`;
        }
        setQueuedMessages((prev) =>
          prev.map((m) => m.id === head.id ? { ...m, status: "error", error } : m),
        );
      });
  }, [workspaceId, sessionId]);

  // Add a message to the back of the local queue. Does NOT call sendAsync —
  // the message will be sent when notifyIdle() is called.
  const enqueue = useCallback((text: string) => {
    if (!workspaceId || !sessionId) return;
    const id = "msg_" + uid();
    const msg: QueuedMessage = { id, text, status: "pending" };
    setQueuedMessages((prev) => [...prev, msg]);
  }, [workspaceId, sessionId]);

  // Called by ChatPage when session.status=idle arrives via SSE.
  // Drains the next pending item from the queue.
  const notifyIdle = useCallback(() => {
    setQueuedMessages((prev) => {
      drainOne(prev);
      return prev;
    });
  }, [drainOne]);

  const remove = (id: string) => {
    setQueuedMessages((prev) => prev.filter((m) => m.id !== id));
  };

  const clear = () => setQueuedMessages([]);

  // reconcile is kept for backward compatibility but is no longer the primary
  // removal mechanism — items are removed on 204 from sendAsync.
  const reconcile = (history: Message[]) => {
    const historyIds = new Set(history.filter((m) => m.role === "user").map((m) => m.id));
    setQueuedMessages((prev) => prev.filter((m) => !historyIds.has(m.id)));
  };

  const retry = async (id: string) => {
    if (!workspaceId || !sessionId) return;
    const msg = queuedMessages.find((m) => m.id === id);
    if (!msg || msg.status !== "error") return;

    try {
      const history = await messagesApi.getHistory(workspaceId, sessionId);
      if (history.some((m) => m.id === id)) {
        remove(id);
        return;
      }
    } catch { /* history fetch failed — fall through to retry send */ }

    // Re-enqueue as pending; it will be sent on the next notifyIdle.
    setQueuedMessages((prev) =>
      prev.map((m) =>
        m.id === id ? { ...m, status: "pending", error: undefined } : m,
      ),
    );
  };

  const dismiss = (id: string) => remove(id);

  const onPhaseChange = (phase: string) => {
    if (phase === "Creating" || phase === "Pending" || phase === "Suspending") {
      setQueuedMessages((prev) =>
        prev.map((m) =>
          m.status === "pending" || m.status === "sending"
            ? { ...m, status: "error", error: "Workspace restarted" }
            : m,
        ),
      );
    }
  };

  return { queuedMessages, enqueue, notifyIdle, remove, retry, dismiss, clear, reconcile, onPhaseChange };
}
