// Copyright (C) 2026 Michael Kao
// SPDX-License-Identifier: AGPL-3.0-or-later

package relay

import (
	"encoding/base64"
	"fmt"
	"strings"
	"text/template"
)

// CloudInitConfig holds the parameters for rendering the relay VM cloud-init.
type CloudInitConfig struct {
	// UpstreamURL is the LLM provider endpoint to proxy to.
	UpstreamURL string
	// Token is the per-VM shared-secret the relay-router presents in the
	// X-Relay-Token header. The VM's relay-proxy rejects any request without
	// a constant-time-matching token. Generated by the controller per provider
	// slot and persisted in the relay-vm-tokens Secret.
	Token string
	// ArtifactURLs are the base mirror URLs the VM downloads the relay-proxy
	// binary from. The cloud-init appends "/<binary>" where <binary> is the
	// arch-resolved name (relay-proxy-arm64 / relay-proxy-amd64) and tries
	// each mirror in order. The controller embeds these at render time —
	// typically a GitHub Release URL plus optional object-storage mirrors.
	// Required: without an artifact URL the systemd unit references a binary
	// that can never arrive on the VM.
	ArtifactURLs []string
	// ArtifactSHA256 is the hex SHA-256 of the relay-proxy binary for the
	// VM's architecture. The cloud-init verifies the downloaded binary
	// against this checksum before exec (security doc §7: supply-chain
	// integrity). Required: downloading without verification is rejected.
	ArtifactSHA256 string
	// BinaryName is the arch-resolved artifact name (relay-proxy-arm64 or
	// relay-proxy-amd64). The controller resolves this from the VM shape via
	// archForShape so the cloud-init downloads the matching binary.
	BinaryName string
}

const cloudInitTemplate = `#cloud-config
package_update: true
packages:
  - curl
write_files:
  - path: /etc/systemd/system/relay-proxy.service
    content: |
      [Unit]
      Description=LLMSafeSpaces Relay Proxy
      After=network-online.target
      Wants=network-online.target

      [Service]
      ExecStart=/usr/local/bin/relay-proxy --upstream={{ .UpstreamURL }} --listen=0.0.0.0:8080 --token={{ .Token }}
      Restart=always
      RestartSec=5
      User=nobody

      [Install]
      WantedBy=multi-user.target
    permissions: "0644"
    owner: root:root
runcmd:
  - sh -c 'set -e; bin=/usr/local/bin/relay-proxy; ok=0; for base in {{ range .ArtifactURLs }}{{ . }} {{ end }}; do if curl -fsSL --connect-timeout 10 "$base/{{ .BinaryName }}" -o "$bin"; then echo "{{ .ArtifactSHA256 }}  $bin" | sha256sum -c - && chmod +x "$bin" && ok=1 && break; fi; done; if [ "$ok" != "1" ]; then echo "FATAL: could not download/verify relay-proxy from any mirror" >&2; exit 1; fi'
  - systemctl enable relay-proxy
  - systemctl start relay-proxy
`

// RenderCloudInit renders the cloud-init userdata for a relay VM.
// The result is base64-encoded as expected by cloud provider APIs.
func RenderCloudInit(cfg CloudInitConfig) (string, error) {
	if cfg.UpstreamURL == "" {
		return "", fmt.Errorf("upstream URL is required")
	}
	if cfg.Token == "" {
		return "", fmt.Errorf("token is required — without it the relay-proxy is an open forwarder to the upstream")
	}
	if len(cfg.ArtifactURLs) == 0 {
		return "", fmt.Errorf("artifact URL is required — without it the relay-proxy binary can never reach the VM")
	}
	if cfg.ArtifactSHA256 == "" {
		return "", fmt.Errorf("artifact SHA-256 is required — security doc §7 mandates integrity verification before exec")
	}
	binary := cfg.BinaryName
	if binary == "" {
		binary = "relay-proxy-arm64"
	}
	cfg.BinaryName = binary

	tmpl, err := template.New("cloud-init").Funcs(template.FuncMap{
		"indent": indentLines,
	}).Parse(cloudInitTemplate)
	if err != nil {
		return "", fmt.Errorf("parse cloud-init template: %w", err)
	}

	var buf strings.Builder
	if err := tmpl.Execute(&buf, cfg); err != nil {
		return "", fmt.Errorf("render cloud-init: %w", err)
	}

	return base64.StdEncoding.EncodeToString([]byte(buf.String())), nil
}

// indentLines indents each line of s by n spaces. Retained for template
// compatibility; the current template does not use it but it is referenced
// in the FuncMap so the template parses without error.
func indentLines(n int, s string) string {
	prefix := strings.Repeat(" ", n)
	lines := strings.Split(s, "\n")
	for i, line := range lines {
		if line != "" {
			lines[i] = prefix + line
		}
	}
	return strings.Join(lines, "\n")
}
