// Copyright (C) 2026 Michael Kao
// SPDX-License-Identifier: AGPL-3.0-or-later

package relay

import "time"

const (
	// InferenceRelayFinalizer is the finalizer name for cleanup on CR deletion.
	InferenceRelayFinalizer = "inferencerelay.llmsafespaces.dev/finalizer"

	// Requeue intervals for different reconcile outcomes.
	requeueProvisioning = 10 * time.Second // waiting for VM to come up
	requeueHealthy      = 30 * time.Second // steady-state health check
	requeueDegraded     = 15 * time.Second // unhealthy relay, faster checking
	requeuePaused       = 5 * time.Minute  // paused fleet, occasional check
	requeueError        = 30 * time.Second // after error, retry soon

	// maxProvisioningAttempts is the max consecutive config-error provisioning
	// attempts before setting ProvisioningFailed condition and stopping retries.
	maxProvisioningAttempts = 3

	// Default shapes per provider.
	defaultShapeAWS = "t4g.micro"
	defaultShapeOCI = "VM.Standard.A1.Flex"
	defaultShapeGCP = "e2-micro"

	// Default regions per provider.
	defaultRegionAWS = "us-east-1"
	defaultRegionOCI = "us-ashburn-1"
	defaultRegionGCP = "us-west1"

	// ConfigMap name managed by the reconciler for relay topology + per-VM tokens.
	routerPeersConfigMap = "relay-router-peers"

	// relayTokensSecret is the K8s Secret holding the per-VM shared-secret
	// tokens the relay-router presents to each relay-proxy. Keyed by provider
	// name (one VM per provider slot). Read-or-generated by ensureRelayToken.
	relayTokensSecret = "relay-vm-tokens"

	// relayTokenBytes is the entropy of each generated token (32 bytes = 256 bits).
	relayTokenBytes = 32

	// Annotation keys read by the reconciler.
	annotationRotate = "relay.llmsafespaces.dev/rotate"
	annotationPaused = "relay.llmsafespaces.dev/paused"
)

// defaultShapeForProvider returns the default VM shape for a provider.
func defaultShapeForProvider(provider string) string {
	switch provider {
	case "aws":
		return defaultShapeAWS
	case "oci":
		return defaultShapeOCI
	case "gcp":
		return defaultShapeGCP
	default:
		return ""
	}
}

// defaultRegionForProvider returns the default region for a provider.
func defaultRegionForProvider(provider string) string {
	switch provider {
	case "aws":
		return defaultRegionAWS
	case "oci":
		return defaultRegionOCI
	case "gcp":
		return defaultRegionGCP
	default:
		return ""
	}
}
