name: Build Runtime Images

on:
  push:
    branches: [ main ]
    paths:
      - 'runtimes/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'runtimes/**'
  release:
    types: [published]

env:
  REGISTRY: ghcr.io
  BASE_IMAGE: lenaxia/llmsafespace/base
  PYTHON_IMAGE: lenaxia/llmsafespace/python
  NODEJS_IMAGE: lenaxia/llmsafespace/nodejs
  GO_IMAGE: lenaxia/llmsafespace/go

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.BASE_IMAGE }}

      - name: Build and push base image
        uses: docker/build-push-action@v4
        with:
          context: ./runtimes/base
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run Trivy vulnerability scanner on base
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.REGISTRY }}/${{ env.BASE_IMAGE }}:${{ steps.meta.outputs.version }}
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Build and push Python image
        uses: docker/build-push-action@v4
        with:
          context: ./runtimes/python
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.REGISTRY }}/${{ env.PYTHON_IMAGE }}:${{ steps.meta.outputs.version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push Node.js image
        uses: docker/build-push-action@v4
        with:
          context: ./runtimes/nodejs
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.REGISTRY }}/${{ env.NODEJS_IMAGE }}:${{ steps.meta.outputs.version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push Go image
        uses: docker/build-push-action@v4
        with:
          context: ./runtimes/go
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.REGISTRY }}/${{ env.GO_IMAGE }}:${{ steps.meta.outputs.version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Upload Trivy scan results
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'
